# Starter pipeline

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      export shaked=new
      for i in $(cat envs); do export $i; done

- task: CmdLine@2
  inputs:
    script: 'set'
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

- task: MSBuild@1
  inputs:
    solution: 'CPP/Modern CPP/CppStringView/*.cbproj'